spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379

  #上传文件限制大小10mb
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB


#    映射下划线到驼峰命名,开启驼峰命名和下划线命名的自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true



